bundle:
    name: DemoBundle
    description: Demobundle provides content types for new websites
    author: e.chau <eric.chau@lp-digital.fr>
    version: 1
    enable: true
    config_per_site: false
